Feature/user entity
Amething/awesome-amething-server pull request #3
Opened 2023-05-07 20:39 UTC by Sinawe4

## 작업 내용
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/41749052/236701197-949f5d4a-d026-4c46-abc1-b04d6bb365ce.png">
해당 ERD를 참고하여 각 엔티티를 구현하였습니다.

## 궁금한 점

각 엔티티에  프로퍼티를 primary constructor로 초기화 하였는데 이러면 null 값이 들어올 가능성이 생기지 않나요?
IDE 차원에서도 secondary constructor를 통해 엔티티의 모든 String의 값을 초기화 하는것을 권장하더군요

2023-05-08 13:59 UTC, siwony requested changes
수고했습니다 리뷰 확인해주시고 
![image](https://user-images.githubusercontent.com/62932968/236843562-6a53ca3d-5cae-46d7-ba29-497e100c6938.png)
파일 끝날 때 개행 한번씩 해주세요 https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2023-05-08 13:59 UTC, siwony commented on src/main/kotlin/com/awesome/amething/domain/answer/answer.kt
> +    var description : String = description
딱히 전처리 하는 과정이 없어 생성자로 선언해도 좋을 것 같아요

2023-05-08 13:59 UTC, siwony commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +class User (username : String, password : String, nickname : String, bio : String, profilePicture : String, refreshToken : String, role: AuthenticatorRole) : UserDetails{
이것도 마찬가지로 생성자에 한번에 선언해도 좋을 것 같습니다

2023-05-08 13:59 UTC, siwony commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +import org.springframework.security.core.userdetails.UserDetails
domain entity에 security 관련된 의존성이 들어가도 될 지 생각해보세요

2023-05-08 13:59 UTC, siwony commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +class User (username : String, password : String, nickname : String, bio : String, profilePicture : String, refreshToken : String, role: AuthenticatorRole) : UserDetails{
UserDetails를 user entity에 바로 구현하는게 아니라 UserDetails 구현체 하나 만들어서 UserEntity를 가져도 괜찮을 것 같아요 

```kotlin
class UserDetailsImpl(
   val user: UserEntity
) : UserDetails {
... 생략
}
```

2023-05-08 14:13 UTC, siwony commented
> 각 엔티티에 프로퍼티를 primary constructor로 초기화 하였는데 이러면 null 값이 들어올 가능성이 생기지 않나요?

추가로 해당 의미가 뭔지 잘 모르겠습니다 자세히 설명 부탁드립니다 null값이 들어올 가능성의 예시가 궁금하네요

2023-05-08 22:31 UTC, key-del-jeeinho reviewed
수고하셧습니다!!!
혹 Entity와 도메인의 모델을 분리하는 방향은 어떻게 생각하시나요??

2023-05-08 22:31 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/question/Question.kt
> +    val id : Long? = null
이부분 id를 은닉한 이유가 있을까요??

2023-05-08 22:31 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/question/Question.kt
> +    var title : String = title
현재 엔티티가 Domain처럼 사용되고있는 것 같은데, title 등에 대한 접근을 domain method를 통해 하도록 하고 setter를 은닉시키는건 어떨까요?
비즈니스 로직 외의 로직이 setter를 통해 수행될 가능성이 있을 것 같습니다.

2023-05-08 22:31 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +    @Enumerated
다른부분들 처럼 직렬화 전략 (type) 명시되면 좋을 것 같습니다.

2023-05-08 22:31 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +class User (username : String, password : String, nickname : String, bio : String, profilePicture : String, refreshToken : String, role: AuthenticatorRole) : UserDetails{
동의해요. UserEntity가 Jpa, Domain, SpringSecurity 세 기술/구조에 대한 책임을 담당할 경우, 결합도가 높아지는것이 우려됩니다.

2023-05-08 22:31 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +class User (username : String, password : String, nickname : String, bio : String, profilePicture : String, refreshToken : String, role: AuthenticatorRole) : UserDetails{
+ 분리할 경우 getAuthorities같은 getter들은 kotlin의 property 생성 후 getter를 override하여 사용하거나, 아예 UserDetailsImpl쪽으로 책임을 위임해도 좋을 것 같습니다.

2023-05-08 22:31 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +        TODO("Not yet implemented")
오버스팩일수도있지만, 이런부분 Kotlin opt in 으로 확실히 사용되지 않도록 명시되어도 좋을 것 같아요.
ex, 
```kotlin
@RequiresOptIn(message = "This API is experimental. It may be changed in the future without notice.")
@Retention(AnnotationRetention.BINARY)
@Target(AnnotationTarget.CLASS, AnnotationTarget.FUNCTION)
annotation class MyDateTime // Opt-in requirement annotation

@MyDateTime
class DateProvider // A class requiring opt-in
```
- [관련 아티클](https://blog.woong.io/posts/kotlin-opt-in/)
- [공식문서](https://kotlinlang.org/docs/opt-in-requirements.html#propagating-opt-in)

2023-05-08 22:31 UTC, key-del-jeeinho reviewed
수고하셧습니다! 혹 Entity와 도메인의 모델을 분리하는 방향은 어떻게 생각하시나요??

2023-05-08 22:35 UTC, key-del-jeeinho commented
+ @siwony 라인 개행의 경우, ktlint를 도입하여, git hook을 통해 자동으로 formatting되도록 구축해도 좋을 것 같아요! 개발하면서 라인개행이 되었는지 여부를 바로바로 확인하기 어려울 것 같습니다.

시스템화 까지 갈 스팩이 아니라면,[ intellij ktlint plugin(unofficial)](https://plugins.jetbrains.com/plugin/15057-ktlint-unofficial-) 추천드려요. 별도의 gradle 테스크를 실행할 필요 없이 자동으로 라인개행(+ ktlint rule) 에 위반된 error를 잡아줍니다.

2023-05-08 22:39 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +        TODO("Not yet implemented")
도입할 경우, 그냥 @ExperimentalFeature 정도로 어플리케이션 내 공용 어노테이션 만들어두고 사용해도 될 것 같습니다!

2023-05-09 02:04 UTC, siwony commented
@key-del-jeeinho 
> @siwony 라인 개행의 경우, ktlint를 도입하여, git hook을 통해 자동으로 formatting되도록 구축해도 좋을 것 같아요! 개발하면서 라인개행이 되었는지 여부를 바로바로 확인하기 어려울 것 같습니다.

구축 예정입니다 감사합니다.

2023-05-09 02:06 UTC, siwony commented on src/main/kotlin/com/awesome/amething/domain/question/Question.kt
> +    var title : String = title
setter를 은닉시키는게 best지만... 도메인 자체가 단순해서 루즈하게 가져가도 괜찮을 것 같아요

2023-05-09 11:15 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/answer/answer.kt
> +class answer (question : Question, description : String){
코틀린 클래스 네이밍 컨벤션과 다른 것 같습니다. 의도한 내용은 아니라고 생각되어, Answer로 고치면 좋을 것 같습니다.

2023-05-09 11:15 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/answer/answer.kt
> +class answer (question : Question, description : String){
+ 엔티티에서 프로퍼티를 생성자와 분리한 이유가 있을까요?? 
별도로 init 블록 등에서 생성자로 들어간 인자값에 대한 전처리 로직을 수행하는게 아니라면 생성자 안에 프로퍼티가 들어가도 좋을 것 같습니다.

2023-05-09 11:20 UTC, key-del-jeeinho commented
> 각 엔티티에 프로퍼티를 primary constructor로 초기화 하였는데 이러면 null 값이 들어올 가능성이 생기지 않나요?

이부분 혹시 primary constructor 의 body가 없다는 맥락의 이야기(question = question 이 안됨)일까요??
맞다면 이부분은 init 블록으로 처리가 가능하고, 프로퍼티에 직접 생성자 변수를 대입한 부분 또한 init 블록처럼 생성자 호출시 실행되기때문에 문제 없을 것 같습니다.
+ Kotlin에서는 `?`를 통해 nullable임이 명시되지 않는 한 모든 자료구조가 Non null을 보장합니다. 현재 모든 Entity의 프로퍼티에 따로 `?`키워드가 붙지 않은것으로 보입니다.
Non nullable 한 자료구조에 null이 들어가는 경우, 컴파일 에러가 발생하기 때문에 해당 코드 내에서 null에 대한 걱정은 안하셔도 될 것 같아요.

2023-05-09 22:09 UTC, Sinawe4 reviewed
좋은 지적들 전부 감사합니다.
말씀 해주신 내용들을 듣다보니 생성자에 대한 이해가 아직 부족한 것 같습니다.
추가로, 엔티티의 결합성을 낮추는 방법에대해 더 고민 해보겠습니다
아낌 없는 조언 모두 감사드립니다.

2023-05-09 22:09 UTC, Sinawe4 commented on src/main/kotlin/com/awesome/amething/domain/answer/answer.kt
> +class answer (question : Question, description : String){
생성자를 선언하지 않고 프로퍼티를 생성할때, 직접 값을 넣어 초기화 시켜줘야 되기에 프로퍼티와 생성자를 분리하였습니다.
다만  
`init 블록 등에서 생성자로 들어간 인자값에 대한 전처리 로직을 수행하는게 아니라면 생성자 안에 프로퍼티가 들어가도 좋을 것 같습니다. `  라는 말의 의미는 제대로 이해하지 못했습니다.
무슨 뜻인지 해석 한번만 부탁드려도 괜찮을까요?

2023-05-09 22:09 UTC, Sinawe4 commented on src/main/kotlin/com/awesome/amething/domain/question/Question.kt
> +    var title : String = title
저 또한 인호님과 같은 고민을 하여 다양한 정보를 찾아보았습니다.
다만 프로퍼티에 대한 개별적인 접근제어자를 부여하여 setter만 private 하여 은닉화하고, domain method를 통한 접근 방식을 활용한다면 두가지 문제가 발생됩니다.  
1.  코드가 너무 장황해집니다. 
코틀린의 장점 중 하나는 자바의 보일러 플레이트 코드를 상당수 제거해주는 것인데 위 방식은 생성자에 파라미터들도 직접 넣어줘야하고 일일이 초기화 코드를 작성해줘야합니다.
2. 실제 해당 방법으로 코드를 구현했을시 컴파일조차 되지 않습니다.
JPA 는 lazy 로딩과 같은 기법들을 적용하기위해 프록시 객체를 생성하는데 코틀린은 open 이라는 키워드를 붙여주지않는 이상 기본적으로 final class, final method이 됩니다.  그래서 이를 해결하기위해 코틀린에서는`allopen`이라는 플러그인을 사용합니다.
다만 해당 플로그인을 사용하면 property 에도 open 이 붙게되는데 open property 에는 private set 을 지정할 수가 없습니다.

2023-05-09 22:09 UTC, Sinawe4 commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +class User (username : String, password : String, nickname : String, bio : String, profilePicture : String, refreshToken : String, role: AuthenticatorRole) : UserDetails{
생성자에 한번에 선언한다는게 무슨뜻인지 제대로 이해하지 못했습니다..
시간 괜찮으시다면 설명 한번만 부탁드려도 될까요?

2023-05-09 22:09 UTC, Sinawe4 commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +        TODO("Not yet implemented")
좋은 방법인 것 같습니다 
참고하여 프로젝트에 적용시킬 수 있도록 노력해보겠습니다 감사합니다.

2023-05-09 22:24 UTC, Sinawe4 commented
> 이부분 혹시 primary constructor 의 body가 없다는 맥락의 이야기(question = question 이 안됨)일까요??
> 맞다면 이부분은 init 블록으로 처리가 가능하고, 프로퍼티에 직접 생성자 변수를 대입한 부분 또한 init 블록처럼 생성자 호출시 실행되기때문에 문제 없을 것 같습니다.
> + Kotlin에서는 ?를 통해 nullable임이 명시되지 않는 한 모든 자료구조가 Non null을 보장합니다. 현재 모든 Entity의 프로퍼티에 따로 ?키워드가 붙지 않은것으로 보입니다.
> Non nullable 한 자료구조에 null이 들어가는 경우, 컴파일 에러가 발생하기 때문에 해당 코드 내에서 null에 대한 걱정은 안하셔도 될 것 같아요.
> 
> 호옥시 Class '$ClassName' should have ... no args constructor 라는 warning이 나온걸 말씀하신거면 아래 아티클을 참고해주세요.
> 
제가 가지고 있던 의문점을 정확하게 짚어 주셨습니다 감사합니다.
말씀해주신 내용에서 궁금한 점이 한가지 있습니다.
1. 프로퍼티에 직접 생성자 변수를 대입한 부분또한 생성자 호출시에 실행되기에 안전하다고 하셨는데
이 말은 즉슨 데이터가 들어오는 순간에(생성자의 호출)에 실행되기에 문제 없다는 뜻인가요?

또한 말씀해주신 내용처럼 `Class '$ClassName' should have ... no args constructor`라는 워닝이 발생해서 질문 드린게 맞습니다.
다만 이미 해당 플러그인을 사용중이나, 지속해서 해당 워닝이 발생중이며
```
@Entity
class Person(val name: String, val age: Int) {
    private constructor(): this("", 0)
}
```
해당 방식처럼 명시적으로 값을 넣어 처리해야만 사라지더군요.. 그래서 이런식으로 명시적으로 처리 되지 않으면 Null 값이 들어가는건가? 싶은 마음에 질문 드렸습니다. 답변 감사합니다!

2023-05-09 22:28 UTC, Sinawe4 commented
또한 인호님께서 말씀해주신 앤티티와 도메인 모델을 분리하는 방법은 조금 더 공부해본 뒤 적용 할 수 있도록 해보겠습니다!
말씀 해주신 내용에 따르면 결합성을 낮추는데 많은 도움이 될 것 같습니다 감사합니다

2023-05-10 01:11 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/question/Question.kt
> +    val id : Long? = null
생성자에서 id를 받지 않도록 은닉한 이유가 궁금했어요! 
이후 실제 db에서 불러온 엔티티를 사용할때는 id를 지정해줘야하는 때가 있을 것 같아서요

2023-05-10 01:28 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/question/Question.kt
> +    var title : String = title
allopen은 현재도 사용되고있는것으로 알고있어요. JPA의 경우, 리플랙션이라는 기술을 사용하여 엔티티를 구성하기때문에, default constructor(인자값을 받지 않는 생성자) 가 존재하지 않을 경우 오류를 반환하게됩니다. 따라서 세터 은닉여부와는 상관없이 사용되어야해요.
1번의 경우 엔티티가 도메인으로서도 사용되므로 코드가 길어짐을 감안하고도 추가했을때 이익이 더 크다고 생각했는데 @siwony 님 말씀처럼 단순한 도메인이라면 적용하지 않아도 될 것 같습니다!
확인하신 것 같아서 resolve하겠습니다!

2023-05-10 01:28 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +    @Enumerated
@Enumerated(type = STRING) 형태로 어떻게 DB에 저장될지 명시하는 부분이 다른 엔티티의 프로퍼티에는 있으나 해당 프로퍼티에는 누락된 것 같아요.

2023-05-10 01:29 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +        TODO("Not yet implemented")
넵넵! 확인했습니다.

2023-05-10 01:30 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/answer/answer.kt
> +class answer (question : Question, description : String){
생성자에서 default value를 지정하는건 어떻게 생각하시나요??
i> nit 블록 등에서 생성자로 들어간 인자값에 대한 전처리 로직을 수행하는게 아니라면 

=> 해당 값에 대해 추가로 프로퍼티로 저장하기 이전에 검증로직이나 특정 로직이 들어가는게 아니라면 입니다.

2023-05-10 01:32 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/answer/answer.kt
> +    var description : String = description
해당 [커맨트](https://github.com/Amething/awesome-amething-server/pull/3#discussion_r1189268544)도 동일한 내용입니다.
생성자 내에서 프로퍼티를 지정할 수 있어요.

2023-05-10 01:32 UTC, Sinawe4 commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +    @Enumerated
`@Enumerated` 어노테이션에 type 속성이 있다는걸 몰랐네요!
감사해요!

2023-05-10 01:35 UTC, Sinawe4 commented on src/main/kotlin/com/awesome/amething/domain/question/Question.kt
> +    var title : String = title
맞습니다!
코틀린에서 JPA를 사용하려면 결국 말씀해주신 allopen를 계속 사용 할 수 밖에 없기 때문에 
세터의 은닉은 조금 힘들 것 같습니다 (그래서 Exposed를 사용하시는 분들도 계시다고 들었어요)

2023-05-10 01:36 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/user/User.kt
> +class User (username : String, password : String, nickname : String, bio : String, profilePicture : String, refreshToken : String, role: AuthenticatorRole) : UserDetails{
해당 [아티클](https://medium.com/@sket8993/kotlin-%EC%83%9D%EC%84%B1%EC%9E%90-%EC%B4%88%EA%B0%84%EB%8B%A8-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0-b8a61df6fe6) 참고 부탁드려요 ㅎㅎ

2023-05-10 01:42 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/question/Question.kt
> +    var title : String = title
일단 은닉 자체는 가능합니다. 해당 [아티클](https://multifrontgarden.tistory.com/272) 참고하신 것 같은데 아래 아티클도 한본 보시면 가능 할 것 같아요.
다만 해당 케이스에서 효율이 그리 좋진 않을 것 같아서 그대로 진행하셔도 좋을 것 같아요
- [아티클](https://kjgleh.github.io/kotlin/2019/06/11/setter.html)

2023-05-10 04:01 UTC, siwony commented on src/main/kotlin/com/awesome/amething/domain/answer/answer.kt
> +    var description : String = description
생성자에서 프로퍼티를 선언할 수 있습니다
```kotlin
class Answer(
    @OneToOne(fetch = FetchType.LAZY, cascade = [(CascadeType.ALL)])
    @JoinColumn(name = "question_id")
    val question : Question = question

    @Column(name = "answer_description")
    var description : String = description
)
```

2023-05-10 04:05 UTC, siwony approved these changes
반영사항 따로 존재하지 않으면 merge해주세요

2023-05-10 05:15 UTC, key-del-jeeinho commented on src/main/kotlin/com/awesome/amething/domain/answer/answer.kt
> +    var description : String = description
예시첨부 감사드려요 시원님 ㅎㅎ

2023-05-11 10:12 UTC, Sinawe4 commented
## 변경점
1. Class 내에서 생성자로 프로퍼티 선언
2. UserEntity에서 SpringSecurity 관련 Import 제거 (UserDetailsImpl 구현)
---
Question과 Answer은 OneToOne 관계를 유지 할 예정
N+1 관련 문제도 없고 (단방향) 이후 확장성을 고려했을 때 굳이 바꿀 이유가 없다고 판단함.  
  
인호가 피드백해준 Entity와 도메인의 모델의 분리는 어떤식으로 구현해야 할지 감이 안잡힘
조금 더 알아보고 적용할지 말지 판단하겠음

2023-05-11 10:14 UTC, Sinawe4 commented on src/main/kotlin/com/awesome/amething/domain/question/Question.kt
> +    var title : String = title
protected를 사용하면 직접적인 접근은 확실하게 막을 수 있겠군요
새롭게 배웠습니다 좋은 정보 감사합니다!

2023-05-13 13:21 UTC, merged